<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Student;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return Student[]
     */
    public function findByAlphabeticalOrder()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('student')
            ->from('AppBundle:Student', 'student')
            ->orderBy('student.lastName')
            ->getQuery()
            ->getResult();

    }
}
