imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

oneup_flysystem:
    adapters:
        ftp_student_image_adapter:
            ftp:
                host: etudiant.u-pem.fr
                port: ~
                username: '%ftp_user%'
                password: '%ftp_password%'
                root: WWW-perso/cvitae/img/students/
                ssl: false
                timeout: ~
                permPrivate: ~
                permPublic: ~
                passive: ~
        ftp_student_cv_adapter:
            ftp:
                host: etudiant.u-pem.fr
                port: ~
                username: '%ftp_user%'
                password: '%ftp_password%'
                root: WWW-perso/cvitae/files/cv/
                ssl: false
                timeout: ~
                permPrivate: ~
                permPublic: ~
                passive: ~
        ftp_offer_image_adapter:
            ftp:
                host: etudiant.u-pem.fr
                port: ~
                username: '%ftp_user%'
                password: '%ftp_password%'
                root: WWW-perso/cvitae/img/offers/
                ssl: false
                timeout: ~
                permPrivate: ~
                permPublic: ~
                passive: ~
        student_image_adapter:
            dropbox:
                client: app.dropbox_client
                prefix: /img/students
        student_cv_adapter:
            dropbox:
                client: app.dropbox_client
                prefix: /files/cv

    filesystems:
        ftp_student_image_fs:
            adapter: ftp_student_image_adapter
            mount: ftp_student_image_fs
        ftp_student_cv_fs:
            adapter: ftp_student_cv_adapter
            mount: ftp_student_cv_fs
        ftp_offer_image_fs:
            adapter: ftp_offer_image_adapter
            mount: ftp_offer_image_fs
        student_image_fs:
            adapter: student_image_adapter
            mount: student_image_fs
        student_cv_fs:
            adapter: student_cv_adapter
            mount: student_cv_fs

vich_uploader:
    db_driver: orm
    storage:   flysystem

    mappings:
        student_image:
            uri_prefix:         cvitae/img/students
            upload_destination: ftp_student_image_fs
            namer:              namer.student

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        student_cv:
            uri_prefix: cvitae/files/cv
            upload_destination: ftp_student_cv_fs
            namer: namer.student

        offer_image:
            uri_prefix: cvitae/img/offers
            upload_destination: ftp_offer_image_fs
            namer: namer.offer

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

fos_rest:
    param_fetcher_listener: force
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
        include_format: false

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    globals:
        dropbox_client:   "@app.dropbox_client"
        site_name:        C-Vitae
        contact_mail:     contact@cvitae.com
        base_upload_url: "http://perso-etudiant.u-pem.fr/~ojbara/"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        sslmode:  ~
        charset:  UTF8
        mapping_types:
            _int4: integer
            _text: text
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      587
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
