# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    twig.extension.pcr:
        class: Jasny\Twig\PcreExtension
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Jasny\Twig\DateExtension
        tags:
            - { name: twig.extension }
    twig.extensions.text:
        class: Jasny\Twig\TextExtension
        tags:
            - { name: twig.extension }
    namer.student:
        class: AppBundle\Entity\Student
        tags:
            - { name: namer }

    namer.offer:
        class: AppBundle\Entity\Offer
        tags:
            - { name: namer }
    app.utilities:
        class: AppBundle\Utilities
    app.dropbox_client:
            class: Dropbox\Client
            arguments:
                - "aIPRwlwowGIAAAAAAAAE0NBnGFiscWrc6qIiEcumZzHhCJGdmQq50naczkclsugU"
                - "plumeau-magique/1.0"